name: test-gradle-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container: wpilib/roborio-cross-ubuntu:2022-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check code formatting with clang-format
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: './lib'
        extensions: 'h,cpp'
        style: llvm
      continue-on-error: true

    # TODO: Potentially add automagic format commit with EndBug/add-and-commit

    - name: Test compilation of code
      run: chmod +x gradlew && ./gradlew build
