name: clang-format-check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Check Formatting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format for C++ code
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '13'
        check-path: 'lib'
